name: Deploy Static Website to Azure 

 

on: 

  push: 

    branches: 

      - main  # Deploy when the main branch is updated 

 

jobs: 

  build_and_deploy: 

    runs-on: ubuntu-latest 

    steps: 

    - name: Checkout code 

      uses: actions/checkout@v2 

 

    - name: Build and Deploy 

      uses: Azure/static-web-apps-deploy@v1 

      with: 

        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Set this in GitHub Secrets 

        repo_token: ${{ secrets.GITHUB_TOKEN }} 

        action: "upload" 

        output_location: "/"  # Location of your static files 
